AnimalsShelter.Web/ViewModels/AnimalsViewModel.cs
using AnimalsShelter.Data.Model;
using AnimalsShelter.Web.Infrastructure;
using System;
using System.Collections.Generic;
using AutoMapper;
using System.ComponentModel.DataAnnotations;
using AnimalsShelter.Common.Enums;
using System.ComponentModel;
using AnimalsShelter.Web.Models.Animals;
using System.Web;
using Newtonsoft.Json;

namespace AnimalsShelter.Web.ViewModels.Animals
{
    public class AnimalsViewModel : IMapFrom<Animal>, IHaveCustomMappings, IAnimalsViewModel
    {
        public Guid Id { get; set; }
        
        [MinLength(2)]
        [MaxLength(45)]
        public string Name { get; set; }

        [Required]
        public AnimalType Type { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(45)]
        public string Breed { get; set; }

        [Required]
        public GenderType Gender { get; set; }

        [Required]
        [Range(0, int.MaxValue)]
        public int Age { get; set; }

        [Required]
        public SizeType Size { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        public string Address { get; set; }

        [Required]
        [MinLength(5)]
        [MaxLength(13)]
        public string PhoneNumber { get; set; }

        [IgnoreMap]
        public HttpPostedFileBase Image { get; set; }

        //[Required]
        public string ImagePath { get; set; }

        [DisplayName("Is for Adoption")]
        public Boolean IsForAdoption { get; set; }

        [DisplayName("Is for Rehome")]
        public Boolean IsForRehome { get; set; }

        [DisplayName("Is Lost")]
        public Boolean IsLost { get; set; }

        [DisplayName("Is Found")]
        public Boolean IsFound { get; set; }

        public virtual User User { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayName("Created On")]
        public DateTime? CreatedOn { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayName("Modified On")]
        public DateTime? ModifiedOn { get; set; }

        public ICollection<AnimalsViewModel> Animals { get; set; }

        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<Animal, AnimalsViewModel>()
                .ForMember(viewModel => viewModel.ModifiedOn, cfg => cfg.MapFrom(model => model.CreatedOn));
        }
    }
}

AnimalsShelter.Web/Controllers/AnimalController.cs
using AnimalsShelter.Data.Model;
using AnimalsShelter.Services.Contracts;
using AnimalsShelter.Web.ViewModels.Animals;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AnimalsShelter.Web.WebUtils.Contracts;
using Bytes2you.Validation;

namespace AnimalsShelter.Web.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IVerificationProvider verification;
        private readonly IMapper mapper;
        private readonly IUsersService usersService;
        private readonly IAnimalsService animalsService;

        public AnimalController(IVerificationProvider verificationProvider, IMapper mapper, IUsersService usersService, IAnimalsService animalsService)
        {
            //Guard.WhenArgument(verification, nameof(verification)).IsNull().Throw();
            Guard.WhenArgument(mapper, nameof(mapper)).IsNull().Throw();
            Guard.WhenArgument(usersService, nameof(usersService)).IsNull().Throw();
            Guard.WhenArgument(animalsService, nameof(animalsService)).IsNull().Throw();

            this.verification = verificationProvider;
            this.mapper = mapper;
            this.usersService = usersService;
            this.animalsService = animalsService;
        }

        // Get Animals for Adoption
        [HttpGet]
        public ActionResult AnimalsForAdoption(int? page)
        {
            ViewData["Title"] = "Animals for Adoption";

            var animals = this.animalsService
                .GetAll()
                .Where(x => x.IsForAdoption == true)
                .OrderByDescending(x => x.ModifiedOn)
                .ProjectTo<AnimalsViewModel>()
                .ToList();

            var pageNumber = page ?? 1;
            var pageSize = 10;
            return View(animals.ToPagedList(pageNumber, pageSize));
        }

        // Get Animals for Rehome
        [HttpGet]
        public ActionResult AnimalsForRehome(int? page)
        {
            ViewData["Title"] = "Animals for Adoption";

            var animals = this.animalsService
                .GetAll()
                .Where(x => x.IsForRehome == true)
                .OrderByDescending(x => x.ModifiedOn)
                .ProjectTo<AnimalsViewModel>()
                .ToList();

            var pageNumber = page ?? 1;
            var pageSize = 10;
            return View(animals.ToPagedList(pageNumber, pageSize));
        }

        // Get Lost Animals
        [HttpGet]
        public ActionResult LostAnimals(int? page)
        {
            ViewData["Title"] = "Animals for Adoption";

            var animals = this.animalsService
                .GetAll()
                .Where(x => x.IsLost == true)
                .OrderByDescending(x => x.ModifiedOn)
                .ProjectTo<AnimalsViewModel>()
                .ToList();

            var pageNumber = page ?? 1;
            var pageSize = 10;
            return View(animals.ToPagedList(pageNumber, pageSize));
        }

        // Get Found Animals
        [HttpGet]
        public ActionResult FoundAnimals(int? page)
        {
            ViewData["Title"] = "Animals for Adoption";

            var animals = this.animalsService
                .GetAll()
                .Where(x => x.IsFound == true)
                .OrderByDescending(x => x.ModifiedOn)
                .ProjectTo<AnimalsViewModel>()
                .ToList();

            var pageNumber = page ?? 1;
            var pageSize = 10;
            return View(animals.ToPagedList(pageNumber, pageSize));
        }

        // Get All Animals
        [HttpGet]
        public ActionResult Animals(int? page)
        {
            ViewData["Title"] = "Animals";

            var animals = this.animalsService
               .GetAll()
               .OrderByDescending(x => x.ModifiedOn)
               .ProjectTo<AnimalsViewModel>()
               .ToList();

            var pageNumber = page ?? 1;
            var pageSize = 10;
            return View(animals.ToPagedList(pageNumber, pageSize));
        }

        // View Animal Details
        [HttpGet]
        public ActionResult Animal(Guid Id)
        {
            ViewData["Title"] = "Animal Details";

            var animal = this.animalsService
                .GetAll()
                .ProjectTo<AnimalsViewModel>()
                .Single(x => x.Id == Id);

            return View(animal);
        }

        // Add Animal for Adoption
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AddAnimalForAdoption()
        {
            ViewData["Title"] = "Add Animal for Adoption";
            return View(new AnimalsViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult AddAnimalForAdoption(Animal animal)
        {
            var userId = User.Identity.GetUserId();
            var currentUser = this.usersService
                .GetAll()
                .SingleOrDefault(x => x.Id == userId);
            string path = GetFilePath(animal.Image);

            animal.ImagePath = path;
            animal.CreatedOn = DateTime.Now;
            animal.User = currentUser;
            this.animalsService.Add(animal);

            return RedirectToAction("Index", "Manage");
        }

        // Add Animal for Rehome
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult AddAnimalForRehome()
        {
            ViewData["Title"] = "Add Animal for Adoption";

            return View(new AnimalsViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        [ValidateAntiForgeryToken]
        public ActionResult AddAnimalForRehome(Animal animal)
        {
            var userId = User.Identity.GetUserId();
            var currentUser = this.usersService
                .GetAll()
                .SingleOrDefault(x => x.Id == userId);
            string path = GetFilePath(animal.Image);

            animal.ImagePath = path;
            animal.CreatedOn = DateTime.Now;
            animal.User = currentUser;
            this.animalsService.Add(animal);

            return RedirectToAction("Index", "Manage");
        }

        // Add Lost Animal
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult AddLostAnimal()
        {
            ViewData["Title"] = "Add Animal for Adoption";

            return View(new AnimalsViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        [ValidateAntiForgeryToken]
        public ActionResult AddLostAnimal(Animal animal)
        {
            var userId = User.Identity.GetUserId();
            var currentUser = this.usersService
                .GetAll()
                .SingleOrDefault(x => x.Id == userId);
            string path = GetFilePath(animal.Image);

            animal.ImagePath = path;
            animal.CreatedOn = DateTime.Now;
            animal.User = currentUser;
            this.animalsService.Add(animal);

            return RedirectToAction("Index", "Manage");
        }

        // Add Found Animal
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult AddFoundAnimal()
        {
            ViewData["Title"] = "Add Animal for Adoption";

            return View(new AnimalsViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        [ValidateAntiForgeryToken]
        public ActionResult AddFoundAnimal(Animal animal)
        {

            string path = GetFilePath(animal.Image);
            var userId = User.Identity.GetUserId();
            var currentUser = this.usersService
                .GetAll()
                .SingleOrDefault(x => x.Id == userId);

            animal.ImagePath = path;
            animal.CreatedOn = DateTime.Now;
            animal.User = currentUser;
            this.animalsService.Add(animal);

            return RedirectToAction("Index", "Manage");
        }

        // Update Animal Info
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult UpdateAnimal(Guid id)
        {
            ViewData["Title"] = "Update Animal Info";

            var animal = this.animalsService
                .GetAll()
                .ProjectTo<AnimalsViewModel>()
                .Single(x => x.Id == id);

            return View(animal);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateAnimal(Animal animal)
        {
            string path = GetFilePath(animal.Image);
            animal.ImagePath = path;
            this.animalsService.Update(animal);

            return RedirectToAction("Index", "Manage");
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult DeleteAnimal(Guid id)
        {
            var animalToDelete = this.animalsService.GetAll()
                .Single(x => x.Id == id);

            this.animalsService.Delete(animalToDelete);

            return RedirectToAction("Index", "Manage");
        }

        private string GetFilePath(HttpPostedFileBase image)
        {
            string imagePath = string.Empty;

            if (image.ContentLength > 0)
            {
                string fileName = Path.GetFileName(image.FileName);
                string fullPath = Path.Combine(Server.MapPath("~/UploadedFiles"), fileName);
                image.SaveAs(fullPath);

                imagePath = "~/UploadedFiles/" + fileName;
                return imagePath;
            }
            else
            {
                return imagePath;
            }
        }
    }
}

AnimalsShelter.Web/Views/Animal/AddAnimalForAdoption.cshtml
@using AnimalsShelter.Web.ViewModels.Animals;

@model AnimalsViewModel

@{
    ViewBag.Title = "Add Animal for Adoption";
}

<h2>Add Animal for Adoption</h2>

@using (Html.BeginForm("AddAnimalForAdoption", "Animal", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_UploadFilePartial", Model.ImagePath)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Size, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsForAdoption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsForAdoption)
                    @Html.ValidationMessageFor(model => model.IsForAdoption, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AnimalsShelter.Web/Views/Animal/AddAnimalForRehome.cshtml
@using AnimalsShelter.Web.ViewModels.Animals;

@model AnimalsViewModel

@{
    ViewBag.Title = "Add Animal for Rehome";
}

<h2>Add Animal for Rehome</h2>

@using (Html.BeginForm("AddAnimalForRehome", "Animal", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_UploadFilePartial", Model.ImagePath)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Size, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsForRehome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsForRehome)
                    @Html.ValidationMessageFor(model => model.IsForRehome, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AnimalsShelter.Web/Views/Animal/AddFoundAnimal.cshtml
@using AnimalsShelter.Web.ViewModels.Animals;

@model AnimalsViewModel

@{
    ViewBag.Title = "Add Found Animal";
}

<h2>Add Found Animal</h2>

@using (Html.BeginForm("AddFoundAnimal", "Animal", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_UploadFilePartial", Model.ImagePath)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Size, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsFound, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsFound)
                    @Html.ValidationMessageFor(model => model.IsFound, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AnimalsShelter.Web/Views/Animal/AddLostAnimal.cshtml
@using AnimalsShelter.Web.ViewModels.Animals;

@model AnimalsViewModel

@{
    ViewBag.Title = "Add Lost Animal";
}

<h2>Add Lost Animal</h2>

@using (Html.BeginForm("AddAnimalForAdoption", "Animal", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_UploadFilePartial", Model.ImagePath)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Size, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsLost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsLost)
                    @Html.ValidationMessageFor(model => model.IsLost, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>