AnimalsShelter.Web/Controllers/ShelterController.cs
using System.Web.Mvc;

namespace AnimalsShelter.Web.Controllers
{
    public class ShelterController : Controller
    {
        public ActionResult Index()
        {
            ViewData["Title"] = "Animals Shelter";

            return View();
        }

        //[OutputCache(Duration = 3600, VaryByParam = "none")]
        [ChildActionOnly]
        public ActionResult IndexCache()
        {
            return this.PartialView();
        }

        public ActionResult About()
        {
            ViewData["Title"] = "About US";

            return View();
        }

        //[OutputCache(Duration = 3600, VaryByParam = "none")]
        [ChildActionOnly]
        public ActionResult AboutCache()
        {
            return this.PartialView();
        }

        public ActionResult Contact()
        {
            ViewData["Title"] = "Contact Us";

            return View();
        }

        //[OutputCache(Duration = 3600, VaryByParam = "none")]
        [ChildActionOnly]
        public ActionResult ContactCache()
        {
            return this.PartialView();
        }
    }
}

AnimalsShelter.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container">
        <div class="navbar navbar-inverse navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><img id="logo" src="~/Images/logo.png">
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="no-padding">@Html.ActionLink("Home", "Index", "Shelter")</li>
                        <li class="no-padding">@Html.ActionLink("About", "About", "Shelter")</li>
                        <li class="no-padding">@Html.ActionLink("Contact", "Contact", "Shelter")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">
                @*<a href="https://github.com/Vasilev87/AnimalsShelter" target="_blank">
                        <strong>ASP.NET MVC Project</strong>
                    </a>*@
            </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>